# Generated by Django 3.2.11 on 2022-04-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('number', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TverWashApp/static/img/', verbose_name='Фото для галереи')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TverWashApp/static/img/', verbose_name='Фото')),
                ('name', models.CharField(max_length=30, verbose_name='Название услуги')),
                ('about', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('number', models.IntegerField(verbose_name='Телефон')),
                ('address', models.TextField(max_length=100, verbose_name='Адрес')),
                ('wishes', models.TextField(max_length=1000, verbose_name='Пожелания')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TverWashApp/static/img/', verbose_name='Фото')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('about', models.TextField(max_length=1000, verbose_name='Краткая история')),
            ],
        ),
    ]
