# Generated by Django 3.2.5 on 2022-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название услуги')),
                ('about', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
