# Generated by Django 4.0.4 on 2022-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TverWashApp', '0002_auto_20220420_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_back',
            name='number',
        ),
        migrations.RemoveField(
            model_name='sign_up',
            name='number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='number',
        ),
        migrations.AddField(
            model_name='call_back',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sign_up',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон'),
        ),
    ]
