# Generated by Django 4.0.4 on 2022-04-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TverWashApp', '0005_alter_gallery_image_alter_services_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_Up',
            new_name='Call_Appointment',
        ),
        migrations.RenameModel(
            old_name='Call_Back',
            new_name='Call_Request',
        ),
    ]
