# Generated by Django 4.0.4 on 2022-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TverWashApp', '0006_rename_sign_up_call_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото для галереи'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
    ]
